### PR TITLE
updateAll and updateMultiple fix

### LINKED ISSUE #71: collection updateAll
```
<?php
$collection->updateAll(array('field' => 'new value'));
```
`updateAll` and `updateMultiple` takes an array argument and passes it to `update` which throws an Exception
`Operator must be instance of Operator or callable`

### PR DESCRIPTION
**Pull request by m7moud**

### CODE REVIEW

**Comment by m7moud** [comment]
Or you can Update the README, I just noticed that php-mongo-migrator README is different.

**Comment by sokil** [comment]
`Operator` class has more than one method, and you may set it through array too:

```php
<?php

$collection->update([], ['k' => 'v']);
$collection->update([], ['$set' => [['k' => 'v']]);
$collection->update([], ['$push' => [['k' => 'v']]);
```

This bug is fixed in v.1.12.2, can you test it?

And thank you for youtr help and contributions

**Comment by sokil** [comment]
php-mongo-migrator - this tool is for migrations only. it based on this library but used to migrate schamas of documents

**Comment by m7moud** [comment]
I know that php-mongo-migrator is for migrations, but it's README uses the update by passing an operator and not an array, that's what I meant.

**Comment by sokil** [comment]
Now i understand. Second operator accept array (as mongo driver), `Operator` object as in sample in php-mongo-migrator and callable that conficure operator. For be callable is the bast case.

**Pull request closed without merging**
