### PR TITLE
Added method setUpsert

### PR DESCRIPTION
**Pull request by Horrower**
for Persistance batch updates

### CODE REVIEW

**Comment by sokil** [comment]
Can you explain, what this and other pull request do, or add some tests?

**Comment by Horrower** [comment]
Hey. My two pull requests is actually the one pull which adding logic for Upsert method for each document.
http://php.net/manual/en/class.mongoupdatebatch.php#116256

The behavior is: if _id exists - update, if not - insert. 
http://docs.mongodb.org/manual/reference/method/Bulk.find.upsert/

**Comment by sokil** [comment]
Upsert used to create document, if it will not found while trying to update? and when query defined without "_id".

Persistence now suppports only Document instances, so creating document already works wgrough batch insert. 

Give me sample code, which not works now

**Comment by Horrower** [comment]
Insert row with _id "123" and any data, create unit of work with 1 SokilDocument and it's id "123", it will drop duplicate key error. 
If set "upsert"  - it will update document

**Comment by sokil** [comment]
Can you execute test https://github.com/sokil/php-mongo/blob/master/tests/PersistenceTest.php#L134-L155

This test checks update of document, and it must cover your case

**Comment by Horrower** [comment]
Sorry, I forgot to add $set method in my changes.
You need add line " $data = array ('$set' => $data ); " after $data assigns 


$client = new Client();
$collection = $client->getDatabase('test')->getCollection('test_col');

// Lets assume our parsers-spiders discovered new product named iPad with capacity 32gb and product id 555
// we are creating our md5 ID's in Mongo for exlude duplicated products
// for simplify updates in DB we set database ID like site_name + product_id : apple.com+555

$collection->batchDelete();

$sMongoID = md5('555' . 'www.apple.com');

$doc = new Document($collection);
$doc->setId($sMongoID);
$doc->set('manufacturer', 'apple.com');
$doc->set('name', 'iPad');
$doc->set('cap', '32GB');

// document created
$doc->save();

unset($doc);

// then, we modify our parser for discover "color" attribute. 
// second time our parser will parse ppple.com and create product with same id:
$sMongoID = md5('555' . 'www.apple.com');


$doc = new Document($collection);
// creating document wit SAME id
$doc->setId($sMongoID);
// set color
$doc->set('color','white');


$persistence = $client->createPersistence();

/*
$persistence->flush();
*/
// Uncaught exception 'MongoDuplicateKeyException' with message '127.0.0.1:27017:
// insertDocument :: caused by :: 11000 E11000 duplicate key error index:


$doc->setUpsert();

// flag Upsert will set in MongoInsertBatch and it will update document without Exception
$persistence->persist($doc);

$persistence->flush();

// Doc in DB : 
// {"_id":"c5339060bc7e6e7303670d17b85068b8","manufacturer":"apple.com","name":"iPad","cap":"32GB","color":"white"}

**Comment by Horrower** [comment]
I'v added check upsert option for Document.
https://github.com/sokil/php-mongo/pull/106/files

**Pull request closed without merging**
