### PR TITLE
add DBRefs relations support

### PR DESCRIPTION
**Pull request by ramzes13**

### CODE REVIEW

**Comment by sokil** [comment]
Tests fails.

**Comment by ramzes13** [comment]
I think that 'RelationManager' need to be marked as deprecated, and after a while removed. It not respect https://docs.mongodb.com/manual/reference/database-references/ structure

**Comment by sokil** [comment]
Not shure that i understand why this class must be deprecated. RelationManager manages relations between collections (every document of one collection to every document in other collection), DBref is just a convenience to store reference to other document in other collection or even database. It has overhead in stored data because every document must store full collection name and even database name. i think we have different view on relational model of MongoDB. My implementation based on relational models of Doctrine/Yii AR, when some entity may be fetched with all relational entities for an optoman number of requests, DBRef require to do one new request on every documen, because dbref of two documents on same collection may refer to different collections and databases

**Comment by sokil** [comment]
Good example than DBRefs used in this PR as not expected:

```php
<?php

protected function extractMongoIdFromDbRef($dbRef)
 {
     if (is_array($dbRef) && array_key_exists('$id', $dbRef)) {
         return $dbRef['$id'];
      } else {
       if (get_class($dbRef) === 'MongoDBRef') {
             $id = '$id';
              return $dbRef->$id;
          }
     }
 }
```

Collection and database not extracted from dbRef, so why not to use just Id and srote relations in php config, as already implemented in Relation manager? DBRef may be useful only for document-to-document relation

**Comment by ramzes13** [comment]
We have a database with official reference structure (dbRef s), current Relation manager can't handle this structure. 
At the moment DbRefRelationManager use mapping from documents, I can ignore documents relations mappint and use information from DbRef, or keep current structure

**Comment by sokil** [comment]
So, as i understand, current RelationBanager completely acceptable, except it can'g get si drocument from db ref?

**Comment by ramzes13** [comment]
Yes, I make new relation manager to keep existing functionality, RelationManager,  and add  functionality with dbRefs DbRefRelationManager

**Comment by sokil** [comment]
if changes only if format of storing related document id to database (ObjectId and DBRef), there is no reason to publicate whole manager. If some changes will be applied to RelationManager, they will be not applied to DBRefRelationManager, we will obtain bug. 

If you want allow relation manager to understand dbrefs you need to refactot relationManager for support also DBRefs too, not to add whole new class

**Comment by ramzes13** [comment]
I agree with you, during the week I will make this change and commit.

**Comment by sokil** [comment]
https://github.com/sokil/php-mongo#dbrefs

**Pull request closed without merging**
