### PR TITLE
Making sure it's a Document

### PR DESCRIPTION
**Pull request by m7moud**
Making sure it's a Document before adding it to DocumentPool

### CODE REVIEW

**Comment by m7moud** [comment]
I'm not sure how to fix this, the scenario of trying to get non-existent Document should be considered.

**Comment by sokil** [comment]
Why you need this check? If i'll pass wrong id, than i'll get null on 
```
$document = $this->getDocumentDirectly($id);
```

And this null goes to identity map. on next request with same id i'll get null from identity map. 

What do you expect to get in your pull request?

**Comment by m7moud** [comment]
addDocumentToDocumentPool takes an argument of type Document, and don't accept null, throws PHP Fatal Error.

**Comment by sokil** [comment]
You are right. This is really my mistake.

**Comment by m7moud** [comment]
BTW you forgot to release 1.11.4.

**Comment by sokil** [comment]
I don't thisnk so :) Already released

**Pull request merged**
